### ISSUE TITLE
Cannot unzip @WORMGPT V0. zip 

### ISSUE THREAD

**Issue by SyphilisLunchbox** [Catdevzsh/WormGPT-#2]
I'm using termux on my rootless android device. (Android13) 

I tried to unzip the *.zip file using zip. That didn't work. Then I tried using "7z e @WORMGPT V0. zip and that still didnt work. I had a previous version of WormGPT installed via termux but I want WORMGPT3. 
Can anyone offer a fix for this problem? 

![Screenshot_20240718-121153](https://github.com/user-attachments/assets/9fc831a4-1c53-44dd-a81c-bdf717c251f0)

**Comment by ACHolding** [comment]
hehe thats a ez one. ok. - im sick so uh here gos thesrs are by lazygpy autonmoua. DELETE THE FREAKINGTHING and downlonad the latest vresion then ask chatgpt rebuild it the readme. in chatgpt blah blah blah idk
